# Generated by Django 2.2.5 on 2019-09-20 02:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upc', models.CharField(max_length=200, verbose_name='UPC')),
                ('sku', models.CharField(max_length=200, verbose_name='SKU')),
                ('sku_vendor', models.CharField(max_length=200, verbose_name='SKU Vendor')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cost Price')),
                ('drop_fee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Drop Fee')),
                ('shipment_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Shipment Price')),
                ('standard_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Standard Price')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantity')),
                ('condition', models.CharField(max_length=200, verbose_name='Condition')),
                ('handling_time', models.CharField(max_length=200, verbose_name='Handling Time')),
                ('wholesale_name', models.CharField(max_length=200, verbose_name='Wholesale Name')),
                ('is_synced', models.BooleanField(default=False, verbose_name='Synced')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='csv_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Time'),
        ),
        migrations.AddField(
            model_name='store',
            name='csv_update_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Update Number'),
        ),
    ]
