# Generated by Django 2.2.5 on 2019-09-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190919_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='sku',
            field=models.CharField(max_length=200, unique=True, verbose_name='SKU'),
        ),
    ]
