# Generated by Django 2.2.5 on 2019-09-20 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190920_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='csv_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Time'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='csv_filename',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Filename'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='csv_update_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Update Number'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
    ]
