# Generated by Django 2.2.5 on 2019-09-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20190920_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='asin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ASIN'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Item Name'),
        ),
    ]
