# Generated by Django 2.2.5 on 2019-09-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20190925_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='last_execution',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last execution'),
        ),
    ]
