# Generated by Django 2.2.5 on 2019-09-30 10:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_store_last_execution'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSubmissionInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feed_submission_id', models.CharField(max_length=200, verbose_name='Feed Submission ID')),
                ('feed_type', models.CharField(max_length=200, verbose_name='Feed Type')),
                ('submitted_date', models.DateTimeField(verbose_name='Submitted Date')),
                ('feed_processing_status', models.CharField(max_length=200, verbose_name='Feed Processing Status')),
                ('started_processing_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Processing Date')),
                ('completed_processing_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Processing Date')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
        ),
    ]
