# Generated by Django 2.2.5 on 2019-10-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_feedsubmissioninfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='handling_time',
            field=models.IntegerField(verbose_name='Handling Time'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
    ]
