# Generated by Django 2.2.5 on 2019-10-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20191014_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('usedlikenew', 'UsedLikeNew'), ('usedverygood', 'UsedVeryGood'), ('usedgood', 'UsedGood'), ('usedacceptable', 'UsedAcceptable'), ('collectiblelikenew', 'CollectibleLikeNew'), ('collectibleverygood', 'CollectibleVeryGood'), ('collectiblegood', 'CollectibleGood'), ('collectibleacceptable', 'CollectibleAcceptable'), ('refurbished', 'Refurbished'), ('club', 'Club')], max_length=200, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='feed_submission_info',
            field=models.ManyToManyField(blank=True, to='store.FeedSubmissionInfo'),
        ),
    ]
